const console = require(".")

console.log("Hello %s", "World")
console.info("Hello %s", "World")
console.debug("Hello %s", "World")
console.dirxml("Hello %s", "World")
console.table("Hello %s", "World")
console.warn("Hello %s", "World")

console.error("Bye %s", "Bug")
console.trace("Bye %s", "Bug")
console.assert(true, "Hello %s", "World")
console.time("Time")
console.timeLog("Time")
console.timeEnd("Time")
console.count("Count")
console.count("Count")
console.countReset("Count")
console.log({key: "value"}, "Hello", "World")
console.dir(console, {depth: 0})
